spring:
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:local}
  application:
    name: magambell
  jpa:
    hibernate:
      ddl-auto: none
  aws:
    ses:
      access-key: ${AWS_SES_ACCESS_KEY}
      secret-key: ${AWS_SES_SECRET_KEY}
    cf: ${AWS_CF_DISTRIBUTION}
    bucket: ${AWS_S3_BUCKET}

jwt:
  secret-key: ${JWT_SECRET_KEY}
  access-expire-time: 3600
  refresh-expire-time: 86400

oauth:
  kakao-uri: https://kapi.kakao.com/v2/user/me
  google-uri: https://www.googleapis.com/oauth2/v3/userinfo
  naver-uri: https://openapi.naver.com/v1/nid/me

---
spring:
  config:
    activate:
      on-profile: local
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url: jdbc:h2:mem:~/magambell
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true

jwt:
  secret-key: testtesttesttesttesttesttesttesttesttesttest

---
spring:
  config:
    activate:
      on-profile: test
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  aws:
    ses:
      access-key: test
      secret-key: test
    cf: test
    bucket: test

jwt:
  secret-key: testtesttesttesttesttesttesttesttesttesttest

---
spring:
  config:
    activate:
      on-profile: prod
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://${SERVER_HOST}:3306/magambell
    username: ${MARIA_USERNAME}
    password: ${MARIA_PASSWORD}

  jpa:
    database-platform: org.hibernate.dialect.MariaDBDialect
    hibernate:
      ddl-auto: none

