spring:
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:local}
  application:
    name: magambell
  jpa:
    hibernate:
      ddl-auto: none
  aws:
    ses:
      access-key: ${AWS_SES_ACCESS_KEY}
      secret-key: ${AWS_SES_SECRET_KEY}

jwt:
  secret-key: ${JWT_SECRET_KEY}
  access-expire-time: 3600
  refresh-expire-time: 86400

---
spring:
  config:
    activate:
      on-profile: local
  datasource:
    url: jdbc:h2:mem:~/magambell
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true

jwt:
  secret-key: testtesttesttesttesttesttesttesttesttesttest

---
spring:
  config:
    activate:
      on-profile: test
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  aws:
    ses:
      access-key: test
      secret-key: test

jwt:
  secret-key: testtesttesttesttesttesttesttesttesttesttest

---
spring:
  config:
    activate:
      on-profile: prod
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://${SERVER_HOST}:3306/magambell
    username: ${MARIA_USERNAME}
    password: ${MARIA_PASSWORD}

  jpa:
    database-platform: org.hibernate.dialect.MariaDBDialect
    hibernate:
      ddl-auto: none

